const STORE='pruefungswerk.v1';
const template={examId:'ihk-2025-01',title:'Abschlussprüfung – Teil 1',year:2025,questions:[{id:'aufgabe-1',type:'single',prompt:'Fragetext hier eintragen',points:2,options:[{id:'a',text:'Antwort A'},{id:'b',text:'Antwort B'}],answerIds:['b'],solution:'Hier die Lösung und eine kurze Erklärung eintragen.'}]};
let data=loadData(),activeQuiz=null,toastTimer,wissen=null,wissenQuery='';
const $=s=>document.querySelector(s);
function loadData(){try{const d=JSON.parse(localStorage.getItem(STORE));if(d&&Array.isArray(d.profiles)&&Array.isArray(d.exams))return d}catch(e){}return{profiles:[{id:crypto.randomUUID(),name:'Lernprofil 1',stats:{sessions:0,answered:0,correct:0,byExam:{},history:[]}}],activeProfile:null,exams:[]}}
if(!data.activeProfile||!data.profiles.some(p=>p.id===data.activeProfile))data.activeProfile=data.profiles[0].id;
function save(){localStorage.setItem(STORE,JSON.stringify(data))}
function profile(){return data.profiles.find(p=>p.id===data.activeProfile)||data.profiles[0]}
function safeText(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function init(){save();render();$('#importButton').onclick=chooseExam;$('#emptyImportButton').onclick=chooseExam;$('#helpImportButton').onclick=()=>{$('#helpDialog').close();chooseExam()};$('#examFileInput').onchange=importExamFile;$('#profileMenuButton').onclick=openProfiles;$('#profileSelect').onchange=e=>{data.activeProfile=e.target.value;save();render()};$('#newProfileForm').onsubmit=createProfile;$('#exportExamsButton').onclick=exportExams;$('#importProgressButton').onclick=()=>{$('#progressFileInput').value='';$('#progressFileInput').click()};$('#exportProgressButton').onclick=exportProgress;$('#progressFileInput').onchange=importProgress;$('#helpButton').onclick=()=>$('#helpDialog').showModal();$('#downloadTemplateButton').onclick=downloadTemplate;$('#navExams').onclick=()=>document.querySelector('.exam-section').scrollIntoView({behavior:'smooth'});$('#navWissen').onclick=showWissen;$('#navStats').onclick=()=>document.querySelector('.stats-strip').scrollIntoView({behavior:'smooth'});document.querySelector('.mobile-nav a').onclick=e=>{e.preventDefault();if(!$('#wissenView').hidden)hideWissen();else if(!$('#diaryView').hidden)hideDiary();else window.scrollTo({top:0,behavior:'smooth'})};$('#continueButton').onclick=continueLearning;$('#navDiary').onclick=showDiary;}
function render(){const p=profile(),s=p.stats||{sessions:0,answered:0,correct:0,byExam:{},history:[]};$('#profileSelect').innerHTML=data.profiles.map(x=>`<option value="${safeText(x.id)}" ${x.id===p.id?'selected':''}>${safeText(x.name)}</option>`).join('');$('#avatarInitial').textContent=(p.name||'L').trim().slice(0,1).toUpperCase();$('#statSessions').textContent=s.sessions||0;$('#statAnswered').textContent=s.answered||0;$('#statAccuracy').textContent=s.answered?`${Math.round((s.correct||0)/s.answered*100)}%`:'—';const grid=$('#examGrid'),empty=$('#emptyState');grid.innerHTML=data.exams.map((e,i)=>{const es=s.byExam[e.examId]||{answered:0,correct:0,sessions:0},pct=es.answered?Math.round(es.correct/es.answered*100):0;return `<article class="exam-card" data-exam="${safeText(e.examId)}" tabindex="0" role="button" aria-label="Prüfung öffnen: ${safeText(e.title)}"><div class="exam-card-top"><span class="exam-number">PRÜFUNG ${String(i+1).padStart(2,'0')}</span><span class="exam-arrow">↗</span></div><h3>${safeText(e.title)}</h3><div class="exam-meta">${e.year?safeText(e.year):'IHK'} · ${e.questions.length} ${e.questions.length===1?'Aufgabe':'Aufgaben'}</div><div class="exam-progress"><span style="width:${pct}%"></span></div><div class="exam-card-foot"><span>${es.sessions||0} Runden</span><span>${es.answered?pct+'% richtig':'NOCH OFFEN'}</span></div></article>`}).join('');grid.hidden=!data.exams.length;empty.hidden=!!data.exams.length;grid.querySelectorAll('.exam-card').forEach(el=>{el.onclick=()=>openExam(el.dataset.exam);el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openExam(el.dataset.exam)}}});renderDiaryCard();}
function chooseExam(){$('#examFileInput').value='';$('#examFileInput').click()}
function importExamFile(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const obj=JSON.parse(r.result),items=Array.isArray(obj)?obj:[obj];let count=0;for(const exam of items){validateExam(exam);const i=data.exams.findIndex(x=>x.examId===exam.examId);if(i>=0)data.exams[i]=exam;else data.exams.push(exam);count++}save();render();showToast(`${count} Prüfung${count===1?'':'en'} importiert`)}catch(err){showToast(`Import nicht möglich: ${err.message}`)}};r.readAsText(f)}
function validateExam(e){if(!e||typeof e!=='object'||!e.examId||!e.title||!Array.isArray(e.questions)||!e.questions.length)throw Error('examId, title und mindestens eine Frage werden benötigt.');for(const [i,q] of e.questions.entries()){if(!q.id||!q.prompt||!['single','multiple','text'].includes(q.type))throw Error(`Frage ${i+1}: id, prompt und gültiger type fehlen.`);if(q.type!=='text'&&(!Array.isArray(q.options)||q.options.length<2))throw Error(`Frage ${i+1}: mindestens zwei Antwortoptionen nötig.`);if(!Array.isArray(q.answerIds)||q.answerIds.some(a=>!q.options?.some(o=>o.id===a)))throw Error(`Frage ${i+1}: answerIds passen nicht zu den Antwortoptionen.`)} }
function openExam(id){const e=data.exams.find(x=>x.examId===id);if(!e)return;const dialog=document.createElement('dialog');dialog.className='modal';dialog.innerHTML=`<div class="modal-head"><div><p class="eyebrow muted">PRÜFUNG STARTEN</p><h2>${safeText(e.title)}</h2></div><button class="close-button" id="closeExamDialog" aria-label="Schließen">×</button></div><p>${e.questions.length} Aufgaben${e.year?` · ${safeText(e.year)}`:''}. Wähle, wie du üben möchtest.</p><div class="help-actions"><button type="button" class="button button-dark" data-mode="practice">Lernmodus</button><button type="button" class="button button-outline" data-mode="exam">Prüfungsmodus</button></div><p class="note-small"><b>Lernmodus:</b> Lösung und Erklärung nach jeder Antwort.<br><b>Prüfungsmodus:</b> Lösungen erst am Ende; Freitext bewertest du selbst.</p>`;document.body.append(dialog);dialog.querySelector('#closeExamDialog').onclick=()=>{dialog.close();dialog.remove()};dialog.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{const mode=b.dataset.mode;dialog.remove();startQuiz(e,mode)});dialog.showModal()}
function startQuiz(exam,mode){activeQuiz={exam,mode,index:0,answers:[],revealed:false,graded:{},startedAt:Date.now()};$('#homeView').hidden=true;$('#quizView').hidden=false;renderQuestion();window.scrollTo(0,0)}
function renderQuestion(){const qv=$('#quizView'),z=activeQuiz,q=z.exam.questions[z.index],isText=q.type==='text',isMulti=q.type==='multiple',chosen=z.answers[z.index]||[];const progress=Math.round(z.index/z.exam.questions.length*100);qv.innerHTML=`<div class="quiz-wrap"><div class="quiz-top"><button class="back-button" id="quitQuiz">← Übersicht</button><div class="quiz-title">${safeText(z.exam.title)}</div><span class="quiz-mode">${z.mode==='practice'?'LERNMODUS':'PRÜFUNG'}</span></div><div class="quiz-progress"><span style="width:${progress}%"></span></div><p class="question-kicker">AUFGABE ${String(z.index+1).padStart(2,'0')} / ${String(z.exam.questions.length).padStart(2,'0')} · ${safeText(q.type.toUpperCase())}</p><h1 class="question-title">${safeText(q.prompt)}</h1>${isText?`<textarea class="answer-text" id="textAnswer" placeholder="Deine Antwort …">${safeText(chosen[0]||'')}</textarea>`:`<div class="answer-list">${q.options.map(o=>`<label class="answer-option ${chosen.includes(o.id)?'selected':''}"><input type="${isMulti?'checkbox':'radio'}" name="answer" value="${safeText(o.id)}" ${chosen.includes(o.id)?'checked':''}><span>${safeText(o.text)}</span></label>`).join('')}</div>`}<div class="quiz-controls"><span class="points-label">${q.points||1} ${q.points===1?'PUNKT':'PUNKTE'}</span><button class="button button-dark" id="answerAction">${z.mode==='practice'&&!z.revealed?'Antwort prüfen':z.index===z.exam.questions.length-1?'Auswertung ansehen':'Weiter'} <span aria-hidden="true">→</span></button></div><div id="solutionArea"></div></div>`;
qv.querySelector('#quitQuiz').onclick=()=>{const answered=z.answers.some(a=>a&&a.length&&String(a[0]).trim());if(!answered){leaveQuiz();return}const dlg=document.createElement('dialog');dlg.className='modal';dlg.innerHTML=`<div class="modal-head"><div><p class="eyebrow muted">RUNDE UNTERBRECHEN</p><h2>Zurück zur Übersicht?</h2></div></div><p>Du hast schon ${z.answers.filter(a=>a&&a.length&&String(a[0]).trim()).length} von ${z.exam.questions.length} Aufgaben beantwortet. Diese Runde wird nicht in die Statistik übernommen.</p><div class="help-actions"><button type="button" class="button button-dark" id="stayBtn">Weitermachen</button><button type="button" class="button button-outline" id="saveLeaveBtn">Speichern & beenden</button></div>`;document.body.append(dlg);dlg.querySelector('#stayBtn').onclick=()=>{dlg.close();dlg.remove()};dlg.querySelector('#saveLeaveBtn').onclick=()=>{dlg.remove();leaveQuiz(true)};dlg.showModal()};qv.querySelectorAll('input[name=answer]').forEach(inp=>inp.onchange=()=>{if(isMulti){const vals=[...qv.querySelectorAll('input[name=answer]:checked')].map(x=>x.value);z.answers[z.index]=vals;qv.querySelectorAll('.answer-option').forEach(el=>el.classList.toggle('selected',el.querySelector('input').checked))}else{z.answers[z.index]=[inp.value];qv.querySelectorAll('.answer-option').forEach(el=>el.classList.toggle('selected',el.querySelector('input').checked))}});qv.querySelector('#textAnswer')?.addEventListener('input',ev=>z.answers[z.index]=[ev.target.value]);qv.querySelector('#answerAction').onclick=()=>answerAction();if(z.mode==='practice'&&z.revealed)showSolution();}
function answerAction(){const z=activeQuiz,q=z.exam.questions[z.index];if(z.mode==='practice'&&!z.revealed){const a=z.answers[z.index]||[];if(!a.length||!a[0]){showToast('Beantworte zuerst die Frage.');return}z.revealed=true;renderQuestion();showSolution();return}if(z.index<z.exam.questions.length-1){z.index++;z.revealed=false;renderQuestion()}else finishQuiz()}
function isCorrect(q,answer){if(q.manualGrade||q.type==='text'&&!(q.answerIds||[]).length)return Boolean(activeQuiz.graded[q.id]);if(q.type==='text'){const given=String((answer||[''])[0]||'').trim().toLowerCase().replace(/[\s.,€]/g,'');return (q.answerIds||[]).some(a=>String(a).trim().toLowerCase().replace(/[\s.,€]/g,'')===given)}const a=[...(answer||[])].sort(),b=[...(q.answerIds||[])].sort();return a.length===b.length&&a.every((x,i)=>x===b[i])}
function showSolution(){const z=activeQuiz,q=z.exam.questions[z.index],el=$('#solutionArea');if(!el)return;const manual=Boolean(q.manualGrade),correct=manual||q.type==='text'?null:isCorrect(q,z.answers[z.index]);const sourceLinks=(q.sourceNotes||[]).filter(x=>/^https:\/\//.test(x)).map(x=>`<div><a href="${safeText(x)}" target="_blank" rel="noopener noreferrer">Quelle öffnen ↗</a></div>`).join('');el.innerHTML=`<div class="solution-box"><strong>${manual?'SELBSTBEWERTUNG – LÖSUNG NICHT SICHER BESTÄTIGT':q.type==='text'?'MUSTERLÖSUNG':correct?'RICHTIG':'NOCH NICHT RICHTIG'}</strong>${q.type==='text'?`<div>Deine Antwort: ${safeText((z.answers[z.index]||[''])[0])||'—'}</div>`:''}<div>${safeText(q.solution||'Keine zusätzliche Erklärung hinterlegt.')}</div>${sourceLinks?`<div class="note-small" style="margin-top:8px">${sourceLinks}</div>`:''}${manual||q.type==='text'?`<div class="self-grade"><button data-grade="true" class="${z.graded[q.id]===true?'chosen':''}">✓ Richtig</button><button data-grade="false" class="${z.graded[q.id]===false?'chosen':''}">↻ Noch üben</button></div>`:''}</div>`;el.querySelectorAll('[data-grade]').forEach(b=>b.onclick=()=>{z.graded[q.id]=b.dataset.grade==='true';showSolution()})}
function finishQuiz(){const z=activeQuiz;let correct=0,scored=0;z.exam.questions.forEach((q,i)=>{const manual=Boolean(q.manualGrade)||q.type==='text'&&!(q.answerIds||[]).length;if(manual&&z.graded[q.id]===undefined)return;scored++;if(isCorrect(q,z.answers[i]))correct++});const total=z.exam.questions.length,p=profile(),s=p.stats||(p.stats={sessions:0,answered:0,correct:0,byExam:{},history:[]}),es=s.byExam[z.exam.examId]||(s.byExam[z.exam.examId]={sessions:0,answered:0,correct:0});s.sessions++;s.answered+=total;s.correct+=correct;es.sessions++;es.answered+=total;es.correct+=correct;s.history.push({examId:z.exam.examId,date:new Date().toISOString(),correct,scored,total,mode:z.mode});logQuizTime(z);save();const rate=scored?Math.round(correct/scored*100):0;$('#quizView').innerHTML=`<div class="quiz-wrap"><div class="quiz-result"><p class="eyebrow">RUNDE ABGESCHLOSSEN</p><h2>${scored&&correct===scored?'Stark gemacht.':'Guter Lernschritt.'}</h2><p class="result-meta">${safeText(z.exam.title)} · ${scored} von ${total} Aufgaben bewertet</p><div class="result-score">${scored?`${correct}/${scored}`:'—'}</div><p class="result-meta">${scored?`${rate} % der bewerteten Antworten richtig.`:'Keine Antwort wurde automatisch bewertet.'} Nicht sicher bestätigte Aufgaben zählen erst nach deiner Selbstbewertung.</p><div class="result-actions"><button class="button button-light" id="reviewAnswers">Lösungen ansehen</button><button class="button button-outline" id="finishToHome">Zur Übersicht</button></div></div></div>`;$('#reviewAnswers').onclick=()=>reviewQuiz(z);$('#finishToHome').onclick=leaveQuiz;}
function reviewQuiz(z){const rows=z.exam.questions.map((q,i)=>`<div class="solution-box"><strong>AUFGABE ${String(i+1).padStart(2,'0')} · ${isCorrect(q,z.answers[i])?'RICHTIG':'NOCH ÜBEN'}</strong><div>${safeText(q.prompt)}</div><div style="margin-top:8px">${safeText(q.solution||'Keine Erklärung hinterlegt.')}</div></div>`).join('');$('#quizView').innerHTML=`<div class="quiz-wrap"><div class="quiz-top"><button class="back-button" id="reviewBack">← Ergebnis</button><div class="quiz-title">Lösungsübersicht</div><span class="quiz-mode">${safeText(z.exam.title)}</span></div>${rows}<button class="button button-dark" style="margin-top:18px" id="reviewHome">Zur Übersicht</button></div>`;$('#reviewBack').onclick=()=>finishDisplay(z);$('#reviewHome').onclick=leaveQuiz;}
function finishDisplay(z){const total=z.exam.questions.length,correct=z.exam.questions.filter((q,i)=>isCorrect(q,z.answers[i])).length;$('#quizView').innerHTML=`<div class="quiz-wrap"><div class="quiz-result"><p class="eyebrow">RUNDE ABGESCHLOSSEN</p><h2>Dein Ergebnis</h2><p class="result-meta">${safeText(z.exam.title)}</p><div class="result-score">${correct}/${total}</div><div class="result-actions"><button class="button button-light" id="reviewAnswers">Lösungen ansehen</button><button class="button button-outline" id="finishToHome">Zur Übersicht</button></div></div></div>`;$('#reviewAnswers').onclick=()=>reviewQuiz(z);$('#finishToHome').onclick=leaveQuiz;}
function leaveQuiz(savePartial){if(savePartial&&activeQuiz){const z=activeQuiz;let correct=0,scored=0;z.exam.questions.forEach((q,i)=>{const a=z.answers[i];const has=a&&a.length&&String(a[0]).trim();if(!has)return;const manual=Boolean(q.manualGrade)||q.type==='text'&&!(q.answerIds||[]).length;if(manual&&z.graded[q.id]===undefined)return;scored++;if(isCorrect(q,a))correct++});if(scored>0){const p=profile(),s=p.stats||(p.stats={sessions:0,answered:0,correct:0,byExam:{},history:[]}),es=s.byExam[z.exam.examId]||(s.byExam[z.exam.examId]={sessions:0,answered:0,correct:0});s.answered+=scored;s.correct+=correct;es.answered+=scored;es.correct+=correct;s.history.push({examId:z.exam.examId,date:new Date().toISOString(),correct,scored,total:z.exam.questions.length,mode:z.mode,partial:true});logQuizTime(z);save()}}activeQuiz=null;$('#quizView').hidden=true;$('#homeView').hidden=false;render();window.scrollTo(0,0)}
function continueLearning(){if(!data.exams.length){document.querySelector('.exam-section').scrollIntoView({behavior:'smooth'});showToast('Importiere zuerst eine Prüfung.');return}openExam(data.exams[0].examId)}
function openProfiles(){renderProfiles();$('#profileDialog').showModal()}
function renderProfiles(){$('#profileList').innerHTML=data.profiles.map(p=>`<div class="profile-row"><span class="profile-dot">${safeText(p.name.trim().slice(0,1).toUpperCase())}</span><div><strong>${safeText(p.name)}</strong><small>${p.stats?.sessions||0} Quizrunden · eigener Lernstand</small></div>${p.id===data.activeProfile?'<span class="points-label">AKTIV</span>':`<button class="button button-outline" data-use="${safeText(p.id)}">Wechseln</button>`}</div>`).join('');$('#profileList').querySelectorAll('[data-use]').forEach(b=>b.onclick=()=>{data.activeProfile=b.dataset.use;save();$('#profileDialog').close();render()})}
function createProfile(e){e.preventDefault();const name=$('#newProfileName').value.trim();if(!name)return;if(data.profiles.some(p=>p.name.toLowerCase()===name.toLowerCase())){showToast('Dieser Profilname ist bereits vergeben.');return}const p={id:crypto.randomUUID(),name,stats:{sessions:0,answered:0,correct:0,byExam:{},history:[]}};data.profiles.push(p);data.activeProfile=p.id;save();$('#newProfileName').value='';renderProfiles();render();showToast(`Profil „${name}“ erstellt`)}
function download(name,content,type='application/json'){const blob=new Blob([content],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportExams(){if(!data.exams.length){showToast('Es gibt noch keine importierten Prüfungen.');return}download('pruefungswerk-pruefungen.json',JSON.stringify(data.exams,null,2));showToast('Prüfungen exportiert')}
function exportProgress(){download(`lernstand-${profile().name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}.json`,JSON.stringify({format:'pruefungswerk-progress-v1',profile:profile()},null,2));showToast('Lernstand exportiert')}
function importProgress(){const f=$('#progressFileInput').files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result),p=x.profile;if(x.format!=='pruefungswerk-progress-v1'||!p?.name||!p?.stats)throw Error('Datei ist keine Prüfungswerk-Lernstandssicherung.');let name=p.name;if(data.profiles.some(a=>a.name.toLowerCase()===name.toLowerCase()))name+=` (Import)`;data.profiles.push({...p,id:crypto.randomUUID(),name});data.activeProfile=data.profiles[data.profiles.length-1].id;save();render();renderProfiles();showToast('Lernstand als eigenes Profil importiert')}catch(err){showToast(`Import nicht möglich: ${err.message}`)}};r.readAsText(f)}
function downloadTemplate(){download('pruefungswerk-vorlage.json',JSON.stringify(template,null,2));showToast('JSON-Vorlage heruntergeladen')}
function showToast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3000)}
init();
const BUNDLED_VERSION=4;
if(location.protocol!=='file:')fetch('./pruefungen-quiz.json?v='+BUNDLED_VERSION,{cache:'no-store'}).then(r=>r.ok?r.json():null).then(exams=>{if(!Array.isArray(exams))return;if(data.exams.length&&(data.bundledVersion||0)>=BUNDLED_VERSION)return;exams.forEach(validateExam);const own=data.exams.filter(e=>!exams.some(x=>x.examId===e.examId));const had=data.exams.length>0;data.exams=[...exams,...own];data.bundledVersion=BUNDLED_VERSION;save();render();showToast(had?'Prüfungsinhalte wurden aktualisiert':'Sechs Prüfungen wurden bereitgestellt')}).catch(()=>{});
if(location.protocol!=='file:')fetch('./wissen.json').then(r=>r.ok?r.json():null).then(s=>{if(Array.isArray(s))wissen=s}).catch(()=>{});
if('serviceWorker'in navigator&&location.protocol!=='file:')window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));

function showWissen(){$('#homeView').hidden=true;$('#diaryView').hidden=true;$('#quizView').hidden=true;$('#wissenView').hidden=false;renderWissen();window.scrollTo(0,0)}
function hideWissen(){$('#wissenView').hidden=true;$('#homeView').hidden=false;render();window.scrollTo(0,0)}
function renderWissen(){const el=$('#wissenView');if(!el)return;if(!wissen||!wissen.length){el.innerHTML='<div class="quiz-wrap"><div class="quiz-top"><button class="back-button" id="wissenBack">\u2190 \u00dcbersicht</button><div class="quiz-title">Lernhilfe</div><span class="quiz-mode">PROXIMUS 5</span></div><p class="note-small">Die Lernhilfe wurde noch nicht geladen. Lade die App mit Internetverbindung einmal neu.</p></div>';el.querySelector('#wissenBack').onclick=hideWissen;return}const q=(wissenQuery||'').trim().toLowerCase();const list=wissen.filter(s=>!q||(s.title+' '+s.body.join(' ')).toLowerCase().includes(q));el.innerHTML=`<div class="quiz-wrap"><div class="quiz-top"><button class="back-button" id="wissenBack">\u2190 \u00dcbersicht</button><div class="quiz-title">Lernhilfe \u00b7 Proximus 5</div><span class="quiz-mode">WISSEN</span></div><input class="wissen-search" id="wissenSearch" placeholder="Begriff suchen, z. B. \u00dcbersch\u00fcsse, R\u00fcckkaufswert, Bezugsrecht \u2026" value="${safeText(wissenQuery||'')}"><p class="note-small">${q?list.length+' von '+wissen.length+' Abschnitten':'Alle '+wissen.length+' Abschnitte \u2013 tippe zum Aufklappen'}</p><div class="wissen-list">${list.map(s=>`<details class="wissen-card"><summary>${safeText(s.title)}</summary>${s.body.map(l=>`<p>${safeText(l)}</p>`).join('')}</details>`).join('')}</div></div>`;el.querySelector('#wissenBack').onclick=hideWissen;const si=el.querySelector('#wissenSearch');si.oninput=()=>{wissenQuery=si.value;renderWissen();const n=$('#wissenSearch');if(n){n.focus();n.setSelectionRange(n.value.length,n.value.length)}}}

/* ===== Lerntagebuch & Tagesziel (v8) ===== */
let diaryEdit=null;
function dkey(d=new Date()){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function diary(){const p=profile();if(!p.diary)p.diary={goalMin:120,entries:[],timerStart:null,timerTopic:''};if(!Array.isArray(p.diary.entries))p.diary.entries=[];if(!p.diary.goalMin)p.diary.goalMin=120;return p.diary}
function fmtMin(m){m=Math.round(m||0);const h=Math.floor(m/60),r=m%60;return h?`${h} h${r?' '+r+' min':''}`:`${r} min`}
function runningMin(){const d=diary();return d.timerStart?Math.max(0,(Date.now()-d.timerStart)/60000):0}
function dayMin(key){const d=diary();let m=d.entries.filter(e=>e.date===key).reduce((s,e)=>s+(+e.min||0),0);if(key===dkey()&&d.timerStart)m+=runningMin();return m}
function streak(){const d=diary();let n=0,day=new Date();if(dayMin(dkey(day))<d.goalMin)day.setDate(day.getDate()-1);for(let i=0;i<730;i++){if(dayMin(dkey(day))>=d.goalMin){n++;day.setDate(day.getDate()-1)}else break}return n}
function weekDays(){const out=[],t=new Date(),wd=(t.getDay()+6)%7;for(let i=0;i<7;i++){const x=new Date(t);x.setDate(t.getDate()-wd+i);out.push(x)}return out}
function ringSvg(pct,size=118){const r=size/2-9,c=2*Math.PI*r,o=c*(1-Math.min(pct,1));return `<svg class="diary-ring" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}" aria-hidden="true"><circle cx="${size/2}" cy="${size/2}" r="${r}" fill="none" stroke="rgba(255,255,255,.14)" stroke-width="9"/><circle cx="${size/2}" cy="${size/2}" r="${r}" fill="none" stroke="${pct>=1?'#d8f06a':'#e68362'}" stroke-width="9" stroke-linecap="round" stroke-dasharray="${c}" stroke-dashoffset="${o}" transform="rotate(-90 ${size/2} ${size/2})"/></svg>`}
function weekHtml(){const d=diary(),today=dkey(),names=['Mo','Di','Mi','Do','Fr','Sa','So'];return `<div class="diary-week">${weekDays().map((x,i)=>{const k=dkey(x),m=dayMin(k),pct=Math.min(m/d.goalMin,1),fut=k>today;return `<div class="dw-day ${k===today?'is-today':''} ${m>=d.goalMin?'is-done':''} ${fut?'is-future':''}" title="${k}: ${fmtMin(m)}"><div class="dw-bar"><span style="height:${Math.round(pct*100)}%"></span></div><b>${m>=d.goalMin?'✓':fut?'·':Math.round(m)||'–'}</b><small>${names[i]}</small></div>`}).join('')}</div>`}
function weekSum(){return weekDays().reduce((s,x)=>s+dayMin(dkey(x)),0)}
function renderDiaryCard(){const el=$('#diaryCard');if(!el)return;const d=diary(),m=dayMin(dkey()),pct=m/d.goalMin,done=pct>=1,st=streak(),rest=Math.max(0,d.goalMin-m);el.innerHTML=`<div class="diary-main"><div class="diary-ring-wrap">${ringSvg(pct)}<div class="diary-ring-label"><b>${Math.min(999,Math.round(pct*100))}%</b><small>HEUTE</small></div></div><div class="diary-copy"><p class="eyebrow">TAGESZIEL · ${fmtMin(d.goalMin).toUpperCase()}</p><h2>${done?'Ziel erreicht ✓':fmtMin(m)+' geschafft'}</h2><p class="diary-sub">${done?'Stark – heute ist abgehakt. Alles drüber ist Bonus.':'Noch '+fmtMin(rest)+' bis zum Ziel.'} ${st?`<span class="diary-streak">🔥 ${st} ${st===1?'Tag':'Tage'} in Folge</span>`:''}</p><div class="diary-actions"><button class="button button-light" id="dcTimer">${d.timerStart?'■ Timer stoppen · <span id="dcRun">'+fmtMin(runningMin())+'</span>':'▶ Lern-Timer starten'}</button><button class="button button-ghost" id="dcOpen">Tagebuch öffnen</button></div></div></div>${weekHtml()}<p class="diary-weeksum">Diese Woche: <b>${fmtMin(weekSum())}</b> von ${fmtMin(d.goalMin*7)}</p>`;$('#dcTimer').onclick=toggleTimer;$('#dcOpen').onclick=showDiary}
function toggleTimer(){const d=diary();if(d.timerStart){const min=runningMin();const start=new Date(d.timerStart);d.timerStart=null;if(min>=1){addEntry({date:dkey(start),min:Math.round(min),topic:d.timerTopic||'Lernzeit',note:'',src:'timer'});showToast(`${fmtMin(min)} eingetragen`)}else showToast('Unter 1 Minute – nicht gespeichert');d.timerTopic=''}else{d.timerStart=Date.now();showToast('Timer läuft – auch wenn du die App schließt')}save();render();if(!$('#diaryView').hidden)renderDiary()}
function addEntry(e){diary().entries.push({id:crypto.randomUUID(),created:new Date().toISOString(),...e})}
function logQuizTime(z){if(!z||!z.startedAt)return;const d=diary();if(d.timerStart)return;const min=Math.round((Date.now()-z.startedAt)/60000);if(min<1||min>300)return;addEntry({date:dkey(),min,topic:z.exam.title+(z.mode==='exam'?' · Prüfungsmodus':' · Lernmodus'),note:'',src:'quiz'});z.startedAt=null}
setInterval(()=>{const d=data&&data.profiles&&diary();if(d&&d.timerStart){const r=$('#dcRun');if(r)r.textContent=fmtMin(runningMin());const r2=$('#dvRun');if(r2)r2.textContent=fmtMin(runningMin())}},20000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&$('#homeView')&&!$('#homeView').hidden)renderDiaryCard()});
function showDiary(){$('#homeView').hidden=true;$('#quizView').hidden=true;$('#wissenView').hidden=true;$('#diaryView').hidden=false;diaryEdit=null;renderDiary();window.scrollTo(0,0)}
function hideDiary(){$('#diaryView').hidden=true;$('#homeView').hidden=false;render();window.scrollTo(0,0)}
function renderDiary(){const el=$('#diaryView'),d=diary(),today=dkey(),m=dayMin(today);const byDay={};[...d.entries].sort((a,b)=>(b.date+(b.created||'')).localeCompare(a.date+(a.created||''))).forEach(e=>(byDay[e.date]=byDay[e.date]||[]).push(e));const days=Object.keys(byDay).sort().reverse();const ed=diaryEdit?d.entries.find(e=>e.id===diaryEdit):null;const gh=Math.floor(d.goalMin/60),gm=d.goalMin%60;
el.innerHTML=`<div class="quiz-wrap"><div class="quiz-top"><button class="back-button" id="diaryBack">← Übersicht</button><div class="quiz-title">Lerntagebuch</div><span class="quiz-mode">${fmtMin(m)} HEUTE</span></div>
<div class="dv-panel"><p class="eyebrow muted">MEIN TAGESZIEL</p><div class="dv-goal"><label>Stunden<input type="number" id="goalH" min="0" max="12" value="${gh}" inputmode="numeric"></label><label>Minuten<input type="number" id="goalM" min="0" max="55" step="5" value="${gm}" inputmode="numeric"></label><button class="button button-dark" id="goalSave">Ziel speichern</button></div><div class="dv-presets">${[60,90,120,180].map(x=>`<button class="chip ${d.goalMin===x?'chip-on':''}" data-goal="${x}">${fmtMin(x)}</button>`).join('')}</div></div>
<div class="dv-panel"><p class="eyebrow muted">LERN-TIMER</p>${d.timerStart?`<p class="dv-run">Läuft seit ${new Date(d.timerStart).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})} · <b id="dvRun">${fmtMin(runningMin())}</b></p>`:''}<div class="dv-goal"><label class="grow">Thema (optional)<input id="timerTopic" maxlength="60" placeholder="z. B. Lebensversicherung, Prüfung V …" value="${safeText(d.timerTopic||'')}"></label><button class="button ${d.timerStart?'button-coral':'button-dark'}" id="dvTimer">${d.timerStart?'■ Stoppen & eintragen':'▶ Starten'}</button></div><p class="note-small">Quizrunden werden automatisch mit ihrer Dauer eingetragen (außer der Timer läuft schon – dann zählt nichts doppelt).</p></div>
<form class="dv-panel" id="entryForm"><p class="eyebrow muted">${ed?'EINTRAG BEARBEITEN':'LERNZEIT NACHTRAGEN'}</p><div class="dv-form"><label>Datum<input type="date" id="enDate" value="${ed?ed.date:today}" max="${today}" required></label><label>Dauer (Min.)<input type="number" id="enMin" min="1" max="720" value="${ed?ed.min:30}" inputmode="numeric" required></label><label class="full">Was hast du gelernt?<input id="enTopic" maxlength="80" placeholder="z. B. Prüfung III, Kapitel Haftpflicht" value="${ed?safeText(ed.topic||''):''}"></label><label class="full">Notiz / Erkenntnis<textarea id="enNote" maxlength="500" rows="3" placeholder="Was lief gut? Was muss ich wiederholen?">${ed?safeText(ed.note||''):''}</textarea></label></div><div class="help-actions"><button class="button button-dark" type="submit">${ed?'Änderung speichern':'Eintragen'}</button>${ed?'<button class="button button-outline" type="button" id="enCancel">Abbrechen</button>':''}</div></form>
<div class="dv-panel"><p class="eyebrow muted">DIESE WOCHE · ${fmtMin(weekSum())} / ${fmtMin(d.goalMin*7)}</p>${weekHtml()}</div>
<h3 class="dv-h">Einträge</h3>${days.length?days.map(k=>{const tot=byDay[k].reduce((s,e)=>s+(+e.min||0),0),ok=tot>=d.goalMin,dt=new Date(k+'T12:00');return `<div class="dv-day"><div class="dv-day-head"><span>${dt.toLocaleDateString('de-DE',{weekday:'short',day:'2-digit',month:'2-digit',year:'numeric'})}</span><span class="${ok?'ok':'no'}">${fmtMin(tot)} ${ok?'✓ Ziel':'· '+Math.round(tot/d.goalMin*100)+' %'}</span></div>${byDay[k].map(e=>`<div class="dv-entry"><div><strong>${safeText(e.topic||'Lernzeit')}</strong><small>${fmtMin(e.min)} · ${e.src==='quiz'?'Quiz automatisch':e.src==='timer'?'Timer':'manuell'}</small>${e.note?`<p>${safeText(e.note)}</p>`:''}</div><div class="dv-entry-act"><button data-edit="${e.id}" aria-label="Bearbeiten">✎</button><button data-del="${e.id}" aria-label="Löschen">×</button></div></div>`).join('')}</div>`}).join(''):'<p class="note-small">Noch keine Einträge. Starte den Timer oder trag deine erste Lerneinheit nach.</p>'}
<p class="privacy-note">Das Tagebuch gehört zu deinem Profil und wird nur auf diesem Gerät gespeichert. Mit „Lernstand sichern“ auf der Übersicht exportierst du es mit.</p></div>`;
const q=s=>el.querySelector(s);q('#diaryBack').onclick=hideDiary;
q('#goalSave').onclick=()=>{const v=(+q('#goalH').value||0)*60+(+q('#goalM').value||0);if(v<5){showToast('Ziel mindestens 5 Minuten');return}d.goalMin=Math.min(v,960);save();renderDiary();showToast('Tagesziel: '+fmtMin(d.goalMin))};
el.querySelectorAll('[data-goal]').forEach(b=>b.onclick=()=>{d.goalMin=+b.dataset.goal;save();renderDiary();showToast('Tagesziel: '+fmtMin(d.goalMin))});
q('#timerTopic').oninput=e=>{d.timerTopic=e.target.value;save()};
q('#dvTimer').onclick=()=>{d.timerTopic=q('#timerTopic').value.trim();toggleTimer()};
q('#entryForm').onsubmit=ev=>{ev.preventDefault();const date=q('#enDate').value,min=Math.round(+q('#enMin').value);if(!date||!(min>0)){showToast('Datum und Dauer angeben');return}const vals={date,min,topic:q('#enTopic').value.trim()||'Lernzeit',note:q('#enNote').value.trim()};if(ed)Object.assign(ed,vals);else addEntry({...vals,src:'manual'});diaryEdit=null;save();renderDiary();showToast(ed?'Eintrag aktualisiert':fmtMin(min)+' eingetragen')};
q('#enCancel')&&(q('#enCancel').onclick=()=>{diaryEdit=null;renderDiary()});
el.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{diaryEdit=b.dataset.edit;renderDiary();q('#entryForm').scrollIntoView({behavior:'smooth'})});
el.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{if(!confirm('Eintrag löschen?'))return;d.entries=d.entries.filter(e=>e.id!==b.dataset.del);save();renderDiary()})}
