const STORE='pruefungswerk.v1';
const template={examId:'ihk-2025-01',title:'Abschlussprüfung – Teil 1',year:2025,questions:[{id:'aufgabe-1',type:'single',prompt:'Fragetext hier eintragen',points:2,options:[{id:'a',text:'Antwort A'},{id:'b',text:'Antwort B'}],answerIds:['b'],solution:'Hier die Lösung und eine kurze Erklärung eintragen.'}]};
let data=loadData(),activeQuiz=null,toastTimer;
const $=s=>document.querySelector(s);
function loadData(){try{const d=JSON.parse(localStorage.getItem(STORE));if(d&&Array.isArray(d.profiles)&&Array.isArray(d.exams))return d}catch(e){}return{profiles:[{id:crypto.randomUUID(),name:'Lernprofil 1',stats:{sessions:0,answered:0,correct:0,byExam:{},history:[]}}],activeProfile:null,exams:[]}}
if(!data.activeProfile||!data.profiles.some(p=>p.id===data.activeProfile))data.activeProfile=data.profiles[0].id;
function save(){localStorage.setItem(STORE,JSON.stringify(data))}
function profile(){return data.profiles.find(p=>p.id===data.activeProfile)||data.profiles[0]}
function safeText(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function init(){save();render();$('#importButton').onclick=chooseExam;$('#emptyImportButton').onclick=chooseExam;$('#helpImportButton').onclick=()=>{$('#helpDialog').close();chooseExam()};$('#examFileInput').onchange=importExamFile;$('#profileMenuButton').onclick=openProfiles;$('#profileSelect').onchange=e=>{data.activeProfile=e.target.value;save();render()};$('#newProfileForm').onsubmit=createProfile;$('#exportExamsButton').onclick=exportExams;$('#importProgressButton').onclick=()=>{$('#progressFileInput').value='';$('#progressFileInput').click()};$('#exportProgressButton').onclick=exportProgress;$('#progressFileInput').onchange=importProgress;$('#helpButton').onclick=()=>$('#helpDialog').showModal();$('#downloadTemplateButton').onclick=downloadTemplate;$('#navExams').onclick=()=>document.querySelector('.exam-section').scrollIntoView({behavior:'smooth'});$('#navStats').onclick=()=>document.querySelector('.stats-strip').scrollIntoView({behavior:'smooth'});$('#continueButton').onclick=continueLearning;}
function render(){const p=profile(),s=p.stats||{sessions:0,answered:0,correct:0,byExam:{},history:[]};$('#profileSelect').innerHTML=data.profiles.map(x=>`<option value="${safeText(x.id)}" ${x.id===p.id?'selected':''}>${safeText(x.name)}</option>`).join('');$('#avatarInitial').textContent=(p.name||'L').trim().slice(0,1).toUpperCase();$('#statSessions').textContent=s.sessions||0;$('#statAnswered').textContent=s.answered||0;$('#statAccuracy').textContent=s.answered?`${Math.round((s.correct||0)/s.answered*100)}%`:'—';const grid=$('#examGrid'),empty=$('#emptyState');grid.innerHTML=data.exams.map((e,i)=>{const es=s.byExam[e.examId]||{answered:0,correct:0,sessions:0},pct=es.answered?Math.round(es.correct/es.answered*100):0;return `<article class="exam-card" data-exam="${safeText(e.examId)}" tabindex="0" role="button" aria-label="Prüfung öffnen: ${safeText(e.title)}"><div class="exam-card-top"><span class="exam-number">PRÜFUNG ${String(i+1).padStart(2,'0')}</span><span class="exam-arrow">↗</span></div><h3>${safeText(e.title)}</h3><div class="exam-meta">${e.year?safeText(e.year):'IHK'} · ${e.questions.length} ${e.questions.length===1?'Aufgabe':'Aufgaben'}</div><div class="exam-progress"><span style="width:${pct}%"></span></div><div class="exam-card-foot"><span>${es.sessions||0} Runden</span><span>${es.answered?pct+'% richtig':'NOCH OFFEN'}</span></div></article>`}).join('');grid.hidden=!data.exams.length;empty.hidden=!!data.exams.length;grid.querySelectorAll('.exam-card').forEach(el=>{el.onclick=()=>openExam(el.dataset.exam);el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openExam(el.dataset.exam)}}});}
function chooseExam(){$('#examFileInput').value='';$('#examFileInput').click()}
function importExamFile(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const obj=JSON.parse(r.result),items=Array.isArray(obj)?obj:[obj];let count=0;for(const exam of items){validateExam(exam);const i=data.exams.findIndex(x=>x.examId===exam.examId);if(i>=0)data.exams[i]=exam;else data.exams.push(exam);count++}save();render();showToast(`${count} Prüfung${count===1?'':'en'} importiert`)}catch(err){showToast(`Import nicht möglich: ${err.message}`)}};r.readAsText(f)}
function validateExam(e){if(!e||typeof e!=='object'||!e.examId||!e.title||!Array.isArray(e.questions)||!e.questions.length)throw Error('examId, title und mindestens eine Frage werden benötigt.');for(const [i,q] of e.questions.entries()){if(!q.id||!q.prompt||!['single','multiple','text'].includes(q.type))throw Error(`Frage ${i+1}: id, prompt und gültiger type fehlen.`);if(q.type!=='text'&&(!Array.isArray(q.options)||q.options.length<2))throw Error(`Frage ${i+1}: mindestens zwei Antwortoptionen nötig.`);if(!Array.isArray(q.answerIds)||q.answerIds.some(a=>!q.options?.some(o=>o.id===a)))throw Error(`Frage ${i+1}: answerIds passen nicht zu den Antwortoptionen.`)} }
function openExam(id){const e=data.exams.find(x=>x.examId===id);if(!e)return;const dialog=document.createElement('dialog');dialog.className='modal';dialog.innerHTML=`<div class="modal-head"><div><p class="eyebrow muted">PRÜFUNG STARTEN</p><h2>${safeText(e.title)}</h2></div><button class="close-button" id="closeExamDialog" aria-label="Schließen">×</button></div><p>${e.questions.length} Aufgaben${e.year?` · ${safeText(e.year)}`:''}. Wähle, wie du üben möchtest.</p><div class="help-actions"><button type="button" class="button button-dark" data-mode="practice">Lernmodus</button><button type="button" class="button button-outline" data-mode="exam">Prüfungsmodus</button></div><p class="note-small"><b>Lernmodus:</b> Lösung und Erklärung nach jeder Antwort.<br><b>Prüfungsmodus:</b> Lösungen erst am Ende; Freitext bewertest du selbst.</p>`;document.body.append(dialog);dialog.querySelector('#closeExamDialog').onclick=()=>{dialog.close();dialog.remove()};dialog.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{const mode=b.dataset.mode;dialog.remove();startQuiz(e,mode)});dialog.showModal()}
function startQuiz(exam,mode){activeQuiz={exam,mode,index:0,answers:[],revealed:false,graded:{}};$('#homeView').hidden=true;$('#quizView').hidden=false;renderQuestion();window.scrollTo(0,0)}
function renderQuestion(){const qv=$('#quizView'),z=activeQuiz,q=z.exam.questions[z.index],isText=q.type==='text',isMulti=q.type==='multiple',chosen=z.answers[z.index]||[];const progress=Math.round(z.index/z.exam.questions.length*100);qv.innerHTML=`<div class="quiz-wrap"><div class="quiz-top"><button class="back-button" id="quitQuiz">← Übersicht</button><div class="quiz-title">${safeText(z.exam.title)}</div><span class="quiz-mode">${z.mode==='practice'?'LERNMODUS':'PRÜFUNG'}</span></div><div class="quiz-progress"><span style="width:${progress}%"></span></div><p class="question-kicker">AUFGABE ${String(z.index+1).padStart(2,'0')} / ${String(z.exam.questions.length).padStart(2,'0')} · ${safeText(q.type.toUpperCase())}</p><h1 class="question-title">${safeText(q.prompt)}</h1>${isText?`<textarea class="answer-text" id="textAnswer" placeholder="Deine Antwort …">${safeText(chosen[0]||'')}</textarea>`:`<div class="answer-list">${q.options.map(o=>`<label class="answer-option ${chosen.includes(o.id)?'selected':''}"><input type="${isMulti?'checkbox':'radio'}" name="answer" value="${safeText(o.id)}" ${chosen.includes(o.id)?'checked':''}><span>${safeText(o.text)}</span></label>`).join('')}</div>`}<div class="quiz-controls"><span class="points-label">${q.points||1} ${q.points===1?'PUNKT':'PUNKTE'}</span><button class="button button-dark" id="answerAction">${z.mode==='practice'&&!z.revealed?'Antwort prüfen':z.index===z.exam.questions.length-1?'Auswertung ansehen':'Weiter'} <span aria-hidden="true">→</span></button></div><div id="solutionArea"></div></div>`;
qv.querySelector('#quitQuiz').onclick=()=>{if(confirm('Quiz beenden? Deine Antworten aus dieser Runde werden nicht gewertet.'))leaveQuiz()};qv.querySelectorAll('input[name=answer]').forEach(inp=>inp.onchange=()=>{if(isMulti){const vals=[...qv.querySelectorAll('input[name=answer]:checked')].map(x=>x.value);z.answers[z.index]=vals;qv.querySelectorAll('.answer-option').forEach(el=>el.classList.toggle('selected',el.querySelector('input').checked))}else{z.answers[z.index]=[inp.value];qv.querySelectorAll('.answer-option').forEach(el=>el.classList.toggle('selected',el.querySelector('input').checked))}});qv.querySelector('#textAnswer')?.addEventListener('input',ev=>z.answers[z.index]=[ev.target.value]);qv.querySelector('#answerAction').onclick=()=>answerAction();if(z.mode==='practice'&&z.revealed)showSolution();}
function answerAction(){const z=activeQuiz,q=z.exam.questions[z.index];if(z.mode==='practice'&&!z.revealed){const a=z.answers[z.index]||[];if(!a.length||!a[0]){showToast('Beantworte zuerst die Frage.');return}z.revealed=true;renderQuestion();showSolution();return}if(z.index<z.exam.questions.length-1){z.index++;z.revealed=false;renderQuestion()}else finishQuiz()}
function isCorrect(q,answer){if(q.manualGrade||q.type==='text'&&!(q.answerIds||[]).length)return Boolean(activeQuiz.graded[q.id]);if(q.type==='text'){const given=String((answer||[''])[0]||'').trim().toLowerCase().replace(/[\s.,€]/g,'');return (q.answerIds||[]).some(a=>String(a).trim().toLowerCase().replace(/[\s.,€]/g,'')===given)}const a=[...(answer||[])].sort(),b=[...(q.answerIds||[])].sort();return a.length===b.length&&a.every((x,i)=>x===b[i])}
function showSolution(){const z=activeQuiz,q=z.exam.questions[z.index],el=$('#solutionArea');if(!el)return;const manual=Boolean(q.manualGrade),correct=manual||q.type==='text'?null:isCorrect(q,z.answers[z.index]);const sourceLinks=(q.sourceNotes||[]).filter(x=>/^https:\/\//.test(x)).map(x=>`<div><a href="${safeText(x)}" target="_blank" rel="noopener noreferrer">Quelle öffnen ↗</a></div>`).join('');el.innerHTML=`<div class="solution-box"><strong>${manual?'SELBSTBEWERTUNG – LÖSUNG NICHT SICHER BESTÄTIGT':q.type==='text'?'MUSTERLÖSUNG':correct?'RICHTIG':'NOCH NICHT RICHTIG'}</strong>${q.type==='text'?`<div>Deine Antwort: ${safeText((z.answers[z.index]||[''])[0])||'—'}</div>`:''}<div>${safeText(q.solution||'Keine zusätzliche Erklärung hinterlegt.')}</div>${sourceLinks?`<div class="note-small" style="margin-top:8px">${sourceLinks}</div>`:''}${manual||q.type==='text'?`<div class="self-grade"><button data-grade="true" class="${z.graded[q.id]===true?'chosen':''}">✓ Richtig</button><button data-grade="false" class="${z.graded[q.id]===false?'chosen':''}">↻ Noch üben</button></div>`:''}</div>`;el.querySelectorAll('[data-grade]').forEach(b=>b.onclick=()=>{z.graded[q.id]=b.dataset.grade==='true';showSolution()})}
function finishQuiz(){const z=activeQuiz;let correct=0,scored=0;z.exam.questions.forEach((q,i)=>{const manual=Boolean(q.manualGrade)||q.type==='text'&&!(q.answerIds||[]).length;if(manual&&z.graded[q.id]===undefined)return;scored++;if(isCorrect(q,z.answers[i]))correct++});const total=z.exam.questions.length,p=profile(),s=p.stats||(p.stats={sessions:0,answered:0,correct:0,byExam:{},history:[]}),es=s.byExam[z.exam.examId]||(s.byExam[z.exam.examId]={sessions:0,answered:0,correct:0});s.sessions++;s.answered+=total;s.correct+=correct;es.sessions++;es.answered+=total;es.correct+=correct;s.history.push({examId:z.exam.examId,date:new Date().toISOString(),correct,scored,total,mode:z.mode});save();const rate=scored?Math.round(correct/scored*100):0;$('#quizView').innerHTML=`<div class="quiz-wrap"><div class="quiz-result"><p class="eyebrow">RUNDE ABGESCHLOSSEN</p><h2>${scored&&correct===scored?'Stark gemacht.':'Guter Lernschritt.'}</h2><p class="result-meta">${safeText(z.exam.title)} · ${scored} von ${total} Aufgaben bewertet</p><div class="result-score">${scored?`${correct}/${scored}`:'—'}</div><p class="result-meta">${scored?`${rate} % der bewerteten Antworten richtig.`:'Keine Antwort wurde automatisch bewertet.'} Nicht sicher bestätigte Aufgaben zählen erst nach deiner Selbstbewertung.</p><div class="result-actions"><button class="button button-light" id="reviewAnswers">Lösungen ansehen</button><button class="button button-outline" id="finishToHome">Zur Übersicht</button></div></div></div>`;$('#reviewAnswers').onclick=()=>reviewQuiz(z);$('#finishToHome').onclick=leaveQuiz;}
function reviewQuiz(z){const rows=z.exam.questions.map((q,i)=>`<div class="solution-box"><strong>AUFGABE ${String(i+1).padStart(2,'0')} · ${isCorrect(q,z.answers[i])?'RICHTIG':'NOCH ÜBEN'}</strong><div>${safeText(q.prompt)}</div><div style="margin-top:8px">${safeText(q.solution||'Keine Erklärung hinterlegt.')}</div></div>`).join('');$('#quizView').innerHTML=`<div class="quiz-wrap"><div class="quiz-top"><button class="back-button" id="reviewBack">← Ergebnis</button><div class="quiz-title">Lösungsübersicht</div><span class="quiz-mode">${safeText(z.exam.title)}</span></div>${rows}<button class="button button-dark" style="margin-top:18px" id="reviewHome">Zur Übersicht</button></div>`;$('#reviewBack').onclick=()=>finishDisplay(z);$('#reviewHome').onclick=leaveQuiz;}
function finishDisplay(z){const total=z.exam.questions.length,correct=z.exam.questions.filter((q,i)=>isCorrect(q,z.answers[i])).length;$('#quizView').innerHTML=`<div class="quiz-wrap"><div class="quiz-result"><p class="eyebrow">RUNDE ABGESCHLOSSEN</p><h2>Dein Ergebnis</h2><p class="result-meta">${safeText(z.exam.title)}</p><div class="result-score">${correct}/${total}</div><div class="result-actions"><button class="button button-light" id="reviewAnswers">Lösungen ansehen</button><button class="button button-outline" id="finishToHome">Zur Übersicht</button></div></div></div>`;$('#reviewAnswers').onclick=()=>reviewQuiz(z);$('#finishToHome').onclick=leaveQuiz;}
function leaveQuiz(){activeQuiz=null;$('#quizView').hidden=true;$('#homeView').hidden=false;render();window.scrollTo(0,0)}
function continueLearning(){if(!data.exams.length){document.querySelector('.exam-section').scrollIntoView({behavior:'smooth'});showToast('Importiere zuerst eine Prüfung.');return}openExam(data.exams[0].examId)}
function openProfiles(){renderProfiles();$('#profileDialog').showModal()}
function renderProfiles(){$('#profileList').innerHTML=data.profiles.map(p=>`<div class="profile-row"><span class="profile-dot">${safeText(p.name.trim().slice(0,1).toUpperCase())}</span><div><strong>${safeText(p.name)}</strong><small>${p.stats?.sessions||0} Quizrunden · eigener Lernstand</small></div>${p.id===data.activeProfile?'<span class="points-label">AKTIV</span>':`<button class="button button-outline" data-use="${safeText(p.id)}">Wechseln</button>`}</div>`).join('');$('#profileList').querySelectorAll('[data-use]').forEach(b=>b.onclick=()=>{data.activeProfile=b.dataset.use;save();$('#profileDialog').close();render()})}
function createProfile(e){e.preventDefault();const name=$('#newProfileName').value.trim();if(!name)return;if(data.profiles.some(p=>p.name.toLowerCase()===name.toLowerCase())){showToast('Dieser Profilname ist bereits vergeben.');return}const p={id:crypto.randomUUID(),name,stats:{sessions:0,answered:0,correct:0,byExam:{},history:[]}};data.profiles.push(p);data.activeProfile=p.id;save();$('#newProfileName').value='';renderProfiles();render();showToast(`Profil „${name}“ erstellt`)}
function download(name,content,type='application/json'){const blob=new Blob([content],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportExams(){if(!data.exams.length){showToast('Es gibt noch keine importierten Prüfungen.');return}download('pruefungswerk-pruefungen.json',JSON.stringify(data.exams,null,2));showToast('Prüfungen exportiert')}
function exportProgress(){download(`lernstand-${profile().name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}.json`,JSON.stringify({format:'pruefungswerk-progress-v1',profile:profile()},null,2));showToast('Lernstand exportiert')}
function importProgress(){const f=$('#progressFileInput').files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result),p=x.profile;if(x.format!=='pruefungswerk-progress-v1'||!p?.name||!p?.stats)throw Error('Datei ist keine Prüfungswerk-Lernstandssicherung.');let name=p.name;if(data.profiles.some(a=>a.name.toLowerCase()===name.toLowerCase()))name+=` (Import)`;data.profiles.push({...p,id:crypto.randomUUID(),name});data.activeProfile=data.profiles[data.profiles.length-1].id;save();render();renderProfiles();showToast('Lernstand als eigenes Profil importiert')}catch(err){showToast(`Import nicht möglich: ${err.message}`)}};r.readAsText(f)}
function downloadTemplate(){download('pruefungswerk-vorlage.json',JSON.stringify(template,null,2));showToast('JSON-Vorlage heruntergeladen')}
function showToast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3000)}
init();
const BUNDLED_VERSION=2;
if(location.protocol!=='file:')fetch('./pruefungen-quiz.json?v='+BUNDLED_VERSION,{cache:'no-store'}).then(r=>r.ok?r.json():null).then(exams=>{if(!Array.isArray(exams))return;if(data.exams.length&&(data.bundledVersion||0)>=BUNDLED_VERSION)return;exams.forEach(validateExam);const own=data.exams.filter(e=>!exams.some(x=>x.examId===e.examId));const had=data.exams.length>0;data.exams=[...exams,...own];data.bundledVersion=BUNDLED_VERSION;save();render();showToast(had?'Prüfungsinhalte wurden aktualisiert':'Sechs Prüfungen wurden bereitgestellt')}).catch(()=>{});
if('serviceWorker'in navigator&&location.protocol!=='file:')window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
